### ISSUE TITLE
remove elasticsearch_data_generator operation 

### ISSUE THREAD

**Issue by sotojn** [terascope/elasticsearch-assets#1034]
Would it be safe to remove the ```elasticsearch_data_generator``` since it is no longer used? Inside the ```fetcher.ts``` file on ```line 11``` it says it's deprecated.

File: ```elasticsearch-assets/asset/src/elasticsearch_data_generator/fetcher.ts```
```typescript
07: import { deprecate } from 'util';
08: import { DataGenerator, CounterResults } from './interfaces';
09: import defaultSchema from './data-schema';
10: 
-> 11: const isDeprecated = deprecate(() => {}, 'elasticsearch_data_generator is deprecated, please use data_generator from standard assets');
12: export default class DataGeneratorFetcher extends Fetcher<DataGenerator> {
13:     dataSchema: any;
```

**Comment by godber** [comment]
We appear to have deprecated this processor 3 years ago:

https://github.com/terascope/elasticsearch-assets/blame/f37b26144e065aad6a7c44a58ce94ceb708cf340/asset/src/elasticsearch_data_generator/fetcher.ts#L11

I will have @sotojn remove it from this asset and update the external dependency on the new processor in the standard asset.

**Comment by godber** [comment]
Wow, he's fast!

https://github.com/terascope/standard-assets/pull/721
