### ISSUE TITLE
spaces_reader must be able to use user supplied CA certificate

### ISSUE THREAD

**Issue by godber** [terascope/elasticsearch-assets#1197]
We finally found the internal process that was relying on this unfortunate workaround:

https://github.com/terascope/elasticsearch-assets/pull/1162

Perhaps the `spaces_reader` can be adapted to take a `caCertificate` like we added to the S3 connectors.

I realize this gets intertwined with the es connector, so we will need to consider the possible broader impact of changes to that connector and if we can implement the `spaces_reader` connector first and leave `elasticsearch` related changes for future work that might be OK.

cc @sotojn

**Comment by busma13** [comment]
With the S3 client we added the user defined CA to the default mozilla CAs list built into nodeJS. Do we want to do the same in this instance?

**Comment by godber** [comment]
> With the S3 client we added the user defined CA to the default mozilla CAs list built into nodeJS. Do we want to do the same in this instance?

Yeah, lets just do the same thing if possible.

**Comment by godber** [comment]
The 3.7.2 asset appears to have resolved the issue.  Thanks @busma13
