### ISSUE TITLE
simple_api_reader is broken

### ISSUE THREAD

**Issue by kstaken** [terascope/elasticsearch-assets#43]
Trying to use the simple_api_reader throws the following error.

```
TSError: Slice failed processing, caused by TSError: client.search is not a function
```

**Comment by peterdemartini** [comment]
That may not be related to any change to this bundle, I got a similar error earlier when the elasticsearch client failed to instantiate.

**Comment by peterdemartini** [comment]
Desregard my last comment, I think I see the problem. I will fix it and see to it there is a better test
