### ISSUE TITLE
Test and Yarn errors

### ISSUE THREAD

**Issue by jsnoble** [terascope/elasticsearch-assets#625]
- `yarn upgrade-interactive --latest` is broken, it fails when ran, it only updates a part of them before failing
- the istanbul reporter for all tests is broken, which I believed happened after splitting out the apis to /packages

**Comment by peterdemartini** [comment]
The istanbul reporter issue is a known bug, we probably just have to wait for istanbul and jest to fix it. As for `yarn` we need to switch to yarn 2 to be able to get past this.

**Comment by peterdemartini** [comment]
The yarn upgrade-interactive issue should be fixed now

**Comment by peterdemartini** [comment]
I am going to close this since the istanbul issue is not something we can do anything about
