### ISSUE TITLE
job errors get lost or ignored in  v2.4.0, v2.2.1

### ISSUE THREAD

**Issue by ciorg** [terascope/elasticsearch-assets#635]
Found two examples that seemed similar where job errors are being ignored or lost somewhere.

### error example with incorrect slice size setting:
with version 1.9.1:

config:
```json
"assets": [
        "elasticsearch:1.9.1"
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader",
            "connection": "CONNECTION",
            "index": "INDEX",
            "type": "TYPE",
            "date_field_name": "date",
            "size": 20000
        },
```
* ending job status: `failed`
* errors: TSError:  `Elasticsearch Error: [query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [11305]`

which makes sense because the max_result_window is set at 10,000 and slice size is 20,000.  

same settings with version 2.4.0:

config:
```json
 "assets": [
        "elasticsearch:2.4.0",
    ],
    "operations": [
        {
            "_op": "elasticsearch_reader",
            "connection": "CONNECTION",
            "index": "INDEX",
            "type": "TYPE",
            "date_field_name": "date",
            "size": 20000
        },
```
* ending job status: `completed`
* errors: `none`

But it only reads 10,000 docs from the index then marks the job as completed.  So there is still an issue with the slice size being bigger than the max_results_window, but it's getting lost somewhere. 

### error example with incorrect lifecycle setting:
with version v1.9.1 

config:
```json
 "name": "JOBNAME",
    "lifecycle": "persistent",
    "workers": 1,
    "assets": [
        "elasticsearch:1.9.1"
    ],
```

returns:
```
 Invalid interval parameter, must be manually set while job is in persistent mode
```

with v2.4.0

 config:
```json
"name": "JOBNAME",
    "lifecycle": "persistent",
    "workers": 1,
    "assets": [
        "elasticsearch:2.4.0",
    ],
```

no error returned and when job is started it stays in `initializing` status.  Seems similar to the above example where the error is getting lost.

**Comment by jsnoble** [comment]
fixed in https://github.com/terascope/elasticsearch-assets/pull/640 and  https://github.com/terascope/teraslice/pull/2521
