### ISSUE TITLE
spaces_reader times out with 10 or more slicers

### ISSUE THREAD

**Issue by ciorg** [terascope/elasticsearch-assets#874]
when using the spaces_reader in a teraslice job when I set the slicers to 10 the job failed with this error:
```
TSError: slicer for ex c882e2aa-437b-4385-85a5-7511b5a02903 had an error, shutting down execution, caused by TSError2: HTTP request timed out connecting to API endpoint.\n
```

changing the number of slicers to 1 or 5 worked fine, only saw the error with 10 or more slicers.

job config:
```JSON
{
    "name": "test#spaces_reader",
    "lifecycle": "once",
    "workers": 20,
    "slicers": 10,
    "assets": [
        "elasticsearch:2.7.2",
        "kafka:3.2.2"
    ],
    "memory": 3221225472,
    "cpu": 2,
    "operations": [
        {
            "_op": "spaces_reader",
            "endpoint": "REDACTED",
            "index": "REDACTED",
            "query": "REDACTED"
            "date_field_name": "REDACTED",
            "token": "REDACTED",
            "fields": [
                "REDACTED",
                "REDACTED",
                "REDACTED",
                "REDACTED"
            ],
            "size": 100000
        },
        {
            "_op": "kafka_sender",
            "connection": "REDACTED",
            "topic": "REDACTED",
            "size": 100000
        }
    ]
}
```

changing the job to use the `elasticsearch_reader` instead of the `spaces_reader` worked fine with 10 slicers.

We discussed the possibility of the client timeout setting being shorter than the elasticsearch cluster's timeout setting or maybe the slicers were all being handled by one node instead of a node per slicer.

**Comment by peterdemartini** [comment]
As far as connections go with `got` , there is no connection pool since it uses the node.js [`globalAgent`](https://nodejs.org/dist/latest-v16.x/docs/api/http.html#httpglobalagent) which is defaults to [`Infinity`](https://nodejs.org/dist/latest-v16.x/docs/api/http.html#agentmaxsockets) number of sockets. It is possible to create a connection pool and use keep-alive but this may have other downsides.

Ref: https://github.com/sindresorhus/got/issues/815

**Comment by peterdemartini** [comment]
For the client timeout, it does look like our default is being set to 30 seconds which should definitely be set to 2 minutes https://github.com/terascope/elasticsearch-assets/blob/85cb2cec65c3ff7015dccb1f104c9a032e274fcc/asset/src/spaces_reader_api/schema.ts#L27-L31

**Comment by ciorg** [comment]
interesting, let me give it a try with the timeout changes...that would be an easy fix!

**Comment by ciorg** [comment]
setting the `timeout:120000` works, was able to run a job with 20 workers and 20 slicers.  

I feel silly for not checking for this, but good work @peterdemartini!

Issue is resolved.

**Comment by peterdemartini** [comment]
I am unresolving this because we need to set the default timeout to 2 minutes
