### ISSUE TITLE
Node 18 asset build

### ISSUE THREAD

**Issue by jsnoble** [terascope/elasticsearch-assets#999]
- need to migrate code and ensure assets can be built and work on node 18

**Comment by godber** [comment]
I merged my PR which should add builds for the node 18 assets:

https://github.com/terascope/elasticsearch-assets/pull/1003

I did not bump and versions though.  So we won't see a node 18 asset build until Lesley's PR here is completed:

https://github.com/terascope/elasticsearch-assets/pull/1004

**Comment by godber** [comment]
We can close this once we have a Node 18 build of teraslice we can test this asset on.

**Comment by godber** [comment]
This is long complete.
